name: Test and build erdkotlin

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: macos-latest
    steps:
      # init
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # build and test
      - name: Build and test
        run: mvn --batch-mode --update-snapshots -f pom.xml verify
